/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 30 16:04:32 GMT 2017
 */

package com.github.aguther.dds.routing.dynamic.observer;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class SessionTest {

  @Test(timeout = 4000)
  public void test00() throws Throwable {
    Session session0 = new Session((String) null);
    String string0 = session0.getTopic();
    assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01() throws Throwable {
    Session session0 = new Session("t7;/", "t7;/");
    String string0 = session0.getTopic();
    assertEquals("t7;/", string0);
  }

  @Test(timeout = 4000)
  public void test02() throws Throwable {
    Session session0 = new Session("", (String) null);
    String string0 = session0.getPartition();
    assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03() throws Throwable {
    Session session0 = new Session("", "oL4h~,j_01ZnqMEo9^");
    String string0 = session0.getPartition();
    assertEquals("oL4h~,j_01ZnqMEo9^", string0);
    assertEquals("", session0.getTopic());
  }

  @Test(timeout = 4000)
  public void test04() throws Throwable {
    Session session0 = new Session("", "");
    Session session1 = new Session("", "");
    boolean boolean0 = session0.equals(session1);
    assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05() throws Throwable {
    Session session0 = new Session("");
    Session session1 = new Session("", "Fo|j");
    boolean boolean0 = session0.equals(session1);
    assertEquals("", session1.getTopic());
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06() throws Throwable {
    Session session0 = new Session("");
    Session session1 = new Session((String) null, "");
    boolean boolean0 = session0.equals(session1);
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07() throws Throwable {
    Session session0 = new Session("");
    boolean boolean0 = session0.equals((Object) null);
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08() throws Throwable {
    Session session0 = new Session("");
    boolean boolean0 = session0.equals(session0);
    assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09() throws Throwable {
    Session session0 = new Session("");
    boolean boolean0 = session0.equals("");
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10() throws Throwable {
    Session session0 = new Session("");
    String string0 = session0.getTopic();
    assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11() throws Throwable {
    Session session0 = new Session("");
    session0.hashCode();
  }

  @Test(timeout = 4000)
  public void test12() throws Throwable {
    Session session0 = new Session("");
    String string0 = session0.getPartition();
    assertEquals("", string0);
  }
}
